### PR TITLE
fix: custom err detection [APE-713]

### PR DESCRIPTION
**Pull request by unparalleled-js**
### What I did

Issue with custom errors.

fixes: #126 
Fixes: APE-693

### How I did it

* Detect custom error message
* Raise `ContractLogicError` instead of `VirtualMachineError`
* Pass in Hex of error type. Going to make `eth-tester` use hex str instead of bytes for consistency next

Note this related issue which can further enhance these features: https://github.com/ApeWorX/ape/issues/690
Since we know the ABI, we should be able to do cool stuff here!

### Checklist

- [x] Passes all linting checks (pre-commit and CI jobs)
- [ ] New test cases have been added and are passing
- [x] Documentation has been updated
- [x] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

### CODE REVIEW

**Comment by unparalleled-js** [comment]
`EthTester` gives us: `"execution reverted: b'\\x82\\xb4)\\x00'"`
Is there an easy way to go from the string `"b'\\x82\\xb4)\\x00'"" (note the inner-stringified bytes of the string) to what Hardhat gives us `0x82b42900` ?

So tldr, still not consistent because it is a little cleaner on Hardhat's side after this PR.

**Comment by unparalleled-js** [comment]
@mikeshultz Let me know your thoughts on this, when you can. You create another issue in `ape` core if you want for `eth-tester` and `ape-geth`, but I think all the providers differ when it comes to these at the moment, and hex strings look nicer in error messages over bytes, until we can decode customer Exception classes from the ABI.

**Review by sabotagebeats — APPROVED** [review]
Tested locally, working for me: 
`ContractLogicError: 0x82b42900`

**Comment by mikeshultz** [comment]
> @mikeshultz Let me know your thoughts on this, when you can. You create another issue in `ape` core if you want for `eth-tester` and `ape-geth`, but I think all the providers differ when it comes to these at the moment, and hex strings look nicer in error messages over bytes, until we can decode customer Exception classes from the ABI.

Thanks for fixing this.  For me, the issue was most prevalent because I was running unit tests as well as fork tests and I couldn't use the same test code.

I'm less concerned about having to create the selector than having `ape.reverts()` work the same across providers.  Hex strings are fine with me and I agree they're often human-friendlier.  Looks like this is translating the error correctly.

**Pull request merged**
