### PR TITLE
chore: delete hack

### PR DESCRIPTION
**Pull request by unparalleled-js**
### What I did

fixes: APE-567

### Checklist

- [ ] Passes all linting checks (pre-commit and CI jobs)
- [ ] New test cases have been added and are passing
- [ ] Documentation has been updated
- [ ] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

### CODE REVIEW

**Comment by unparalleled-js** [comment]
requires https://github.com/ApeWorX/ape/pull/1276

**Comment by unparalleled-js** [comment]
We are able to move forward with this until https://github.com/foundry-rs/foundry/issues/4240 is resolved.
For now, the Foundry plugin will not be able to make use of the shared code.

**Comment by unparalleled-js** [comment]
sorry, comment about foundry was meant to go to foundry plugin

**Review by helloibis — APPROVED** [review]

**Review by fubuloubu — APPROVED** [review]
heckuva hack

**Review by NotPeopling2day — APPROVED** [review]

**Comment by unparalleled-js** [comment]
> heckuva hack

for reference, the hack was copying come code from core and changing one thing about.
So not as intense as it seems.

**Pull request merged**
